# Using node js image
FROM node:18-alpine

# Setting up the working directory
WORKDIR /app

# Copying package.json and package-lock.json
COPY package*.json ./

# Installing dependencies
RUN npm install

# Copying the rest of files
COPY . .

# Exposing port
EXPOSE 5173

# Command to start the Vite server
CMD sh -c 'test -f config.js && npm run dev -- --host || cp config-example.js config.js && npm run dev -- --host'
