# Use php image
FROM php:8.2-cli

# Set up the working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    libsqlite3-dev \
    unzip

# Install PHP extensions for Laravel
RUN docker-php-ext-install pdo pdo_sqlite

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy existing application directory contents
COPY . /var/www

# Expose the port for the Laravel application
EXPOSE 8000

# If no .env file exists, copy the .env.example file
RUN test -f .env || cp .env.example .env

# Install PHP dependencies
RUN composer install 

# Migrate and seed the database
RUN php artisan migrate --seed

# Run migration and seed
CMD php artisan serve --host=0.0.0.0 --port=8000
